### ISSUE TITLE
Deprecated property delivery_category is being used

### ISSUE THREAD

**Issue by AsimKhan2019** [nozzlegear/ShopifySharp#1044]
Hi,

I'm using version 6.13 but I'm receiving this complain from Shopify
https://shopify.dev/changelog/removal-of-the-delivery_category-field-on-order-shipping-lines
The endpoint is Order -> Admin • REST though

The only place where I found a similar property is in https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Entities/GraphQL/GraphQLSchema.generated.cs 
by the name deliveryCategory in ShippingLine class.

Could this be causing issue? Will you delete this field where required in the next release?

**Comment by nozzlegear** [comment]
Heye @AsimKhan2019! Sorry for the delay, did you get this fixed? I think the problem is likely your webhook versions which need to be manually updated in the Shopify Partner dashboard. If you log into your partner dashboard and find the settings for your app, there's a configuration page where you can set the **Event Version** specifically for the webhooks that Shopify sends to your app. 

![Screenshot 2024-04-04 at 16 35 06]
(https://github.com/nozzlegear/ShopifySharp/assets/2417276/b290a5ec-6a9c-4f32-a014-cbbd9ac12116)

If the version is old enough, like in my screenshot, they'll send deprecated properties and that can trigger the deprecation warnings.

Let me know if that fixes your problem!

**Comment by AsimKhan2019** [comment]
Thanks @nozzlegear , API health is all good now. :)
