### ISSUE TITLE
How to list order by product ?

### ISSUE THREAD

**Issue by Loocist23** [nozzlegear/ShopifySharp#1045]
Ok so i'm trying to create a multi vendor dashboard and for this i want to get all the orders that are related to a products that my vendor sell

I don't know if i'm clear but if you can help me please

and sorry my first langage isn't english

**Comment by concua1111** [comment]
hey guy! so hard and not good for performance,
you should try to get all the orders and get all the products.
then you can create a function to map this information to make the report.

**Comment by nozzlegear** [comment]
Hey! I agree it's not great for performance, especially if you have a shop with millions of orders. 

I think what I would do is put this into a background service first, so that you're not blocking any sort of UI or frontend javascript while you query this data. In Asp.Net 5+, you can use the [IHostedService](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio) interface to create a service that runs in the background on startup.

For the actual querying though, I can't find any better method than what's been suggested already. Shopify doesn't seem to support anything to look up orders by the product that was purchased as far as I'm aware. I'll think on this and do some experiments! I'm interested in figuring this out.
