### ISSUE TITLE
ShopifyMetaFieldService.ListAsync not returning correct metafields for a product id.

### ISSUE THREAD

**Issue by NormTheThird** [nozzlegear/ShopifySharp#106]
I tried calling this method and passing in the product id and product as the namespace / resource type and it returns nothing.  I then call it with the product id and it returns only one metafield while there are two and the one it returns it from a different namespace.

**Comment by NormTheThird** [comment]
Also metafields are not coming back from object when creating or updating a product.

**Comment by nozzlegear** [comment]
Thanks for reporting this. MetaFields shouldn't be returned when updating or creating something because they're not actually a part of the object in Shopify's API. That's not obvious when using this lib though, because I made the mistake of adding MetaField props to the objects instead of making them an extra parameter of the Update and Create methods. That would be a breaking change, so I'm going to schedule that for the 4.0 release (which will be starting soon).

As for the MetaField service itself not returning the right metafields, I'll take a closer look and run the tests as soon as I get a chance. Could you give me an example that's not working for you?

**Comment by NormTheThird** [comment]
This returns an error not found even though there are two metafields tied to this product"

var task = Task.Run(async () => await this.ShopifyMetaFieldService.ListAsync(9897094927, "Product"));
var result = task.Result;


This returns one item from namespace "shopify_pos" but neither of the two product ones"

var task = Task.Run(async () => await this.ShopifyMetaFieldService.ListAsync(9897094927));
var result = task.Result;

Thanks for adding that to the next release.

**Comment by darkstar74** [comment]
For the first example the resource type should be lower case. Products is not valid resource type in the Shopify API. The service should be updated to force the resource type to lower case.

For the second example if the resource type is null the service assumes it needs to get shop metafields.

See https://help.shopify.com/api/reference/metafield#index the section labelled Get all metafields that belong to a store.

**Comment by NormTheThird** [comment]
tried this and it worked.  Thanks for the help.

var task = Task.Run(async () => await this.ShopifyMetaFieldService.ListAsync(9897094927, "products"));

**Comment by nozzlegear** [comment]
Glad you got it to work, thanks for the help @darkstar74! I'll make sure to get the lowercase thing documented in the next update.

**Comment by darkstar74** [comment]
Glad to help out. I added resourceType = resourceType.ToLower(); to the MetaField service methods that need it.

I'll get the pull request sorted this weekend.
