### ISSUE TITLE
Question on Billing - Not an issue

### ISSUE THREAD

**Issue by alectec** [nozzlegear/ShopifySharp#122]
This is probably a silly question on something I overlooked....

I'm working with some of the code from the Shopify Handbook.  I added conditions that will create a charge (Recurring, Usage, or OneTime) based on a PlanType I setup.  How do you create a free app?  Is it the absence of a charge?  I tried just setting the price to zero but it throws an exception.

**Comment by nozzlegear** [comment]
That's a good question! If you simply don't create a subscription charge then your app will always be free for the merchant that installs it. Once you've got their access token you should be good to go, it's definitely not a requirement to create a billing charge. If you're trying to do a sort of tiered payment model though (e.g. 1000 free X per month), then you're going to wind up tracking your own custom "subscription" start and end date each month. 

Much to my dismay, it looks like Shopify *still* doesn't support this scenario despite me pestering their dev advocates and partners for better billing tools. Fortunately (unfortunately), their billing doesn't support webhooks to let you know when a user's subscription has rolled over either, so I'm not sure how useful that would be right now anyway.

:salt:

That said, depending on your use case, you could create a UsageCharge that's capped at $0.01 and just set the `Terms` to say something like "you're only seeing this because we can't create a free plan, you'll never be charged":

![image](https://cloud.githubusercontent.com/assets/2417276/23918829/83666b38-08c2-11e7-817f-c6dd5f227abb.png)

**Comment by alectec** [comment]
Thanks! That is exactly what I was looking for.  I'll take into account the caveats that you mention, as well.

Right now, I just need a simple free app.  My second and third app will be either recurring or one-time; not sure yet.  I've taken the time to create a white-labeled set of boilerplate code that handles auth, billing, redirects, webhooks, etc (based on your AuntieDot example project) so my next app will just be writing the business logic and handling the UI/UX.   
For now, I'll rework my flow to bypass the charge code when it's marked as a free app.
