### ISSUE TITLE
Submitting code for Discounts

### ISSUE THREAD

**Issue by mobbsie** [nozzlegear/ShopifySharp#123]
Hi,

While I have used GitHub to pull libraries into projects, I have never contributed to a project but feel I could assist with the development of this library as I am finding it really useful myself.

I have downloaded the code using SVN and written code applicable to Discounts which is currently missing from the library.  How do I go about contributing this code?

Cheers,

Andrew

**Comment by nozzlegear** [comment]
Hey Andrew, I'm happy to hear you've got some code you want to contribute! I'm not familiar with SVN at all, but creating a pull request via GitHub isn't *too* terribly hard for your first time. The first thing you'll need to do is "fork" this repository, which you can do by going to the [main repo page](https://github.com/nozzlegear/shopifysharp) and clicking the Fork button at the top right; or you could just navigate straight to the fork link at [https://github.com/nozzlegear/shopifysharp/fork](https://github.com/nozzlegear/shopifysharp/fork). 

Once you've got the repository forked you'll be able to make your own changes. I use Git from the command line, so that process would look something like this:

```bash
# Clone the forked repository
git clone https://github.com/mobbsie/shopifysharp

# Make your changes to ShopifySharp

# Commit your changes
git add -A
git commit -m "Your commit message here, e.g. Added Discount support"

# Push the changes back to your repository
git push origin master
```

If you're not comfortable with the command line you could try using [GitHub's desktop software](https://desktop.github.com/).

Once you've got the code pushed back to your forked repository on GitHub, all you need to do is make a pull request back to this one by going to [https://github.com/nozzlegear/ShopifySharp/pull/new/master](https://github.com/nozzlegear/ShopifySharp/pull/new/master). After that I'll have a chance to review your changes and merge them into the library.

This tutorial does a pretty good job of explaining the pull request: https://www.youtube.com/watch?v=NnBb9NTk-To

**Comment by mobbsie** [comment]
Hi Josh,

Thanks for taking the time to outline the general process. I will try figure out how to do it with SVN (which I am more familiar with) and revert.

The only thing I am a little concerned about is that the new model object I have created is called ShopifyDiscount and you already have a ShopifyDiscountCode model for the discounts one finds in the order objects etc. It may be worthwhile us having a single model object but may require a bit of refactoring.  I am happy to do this but the footprint of the changes will be quite broad and I am not sure if you would rather me just submit it with the additional model object and other changes which are relatively minor so that you can approve the changes more easily and then we do the refactoring at a later stage?  Let me know if you have a preference.

Have a good day / evening. I assume you are based in the US?  I am in South Africa so probably a few hours ahead of you.

Cheers,

Andrew

**Comment by nozzlegear** [comment]
You guessed right, I'm in the US! 😃 I think for now it would be best to include your model as it is just to prevent a lot of extra work that we'll already be going through when I start work on version 4 soon.

**Comment by mobbsie** [comment]
Okay great.  Thanks.  Sorry I am only replying to this now.  I seem to have missed the notification previously sent.  I will upload this as soon as I get back to my desk - I am travelling until 10 April.
