### ISSUE TITLE
Finch is closing down? What other localhost proxy tools do you use?

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#124]
It looks like [Finch ](https://meetfinch.com/)may be closing.
It's a shame it was a good tool.
Does anyone know of any other similar tool?
I thought I may take a look at [ngrok](https://ngrok.com/)...

This is not an issue with ShopifySharp, but I thought it could be useful for everyone...

**Comment by nozzlegear** [comment]
I just got that email yesterday! I was hoping that I'd be able to delay updating the Shopify handbook until .NET Core support was ready, but it looks like I'll need to update it with a Finch replacement sooner than I thought. 

Sad to see them shutting down though, I've been using Finch since they first launched. Ngrok is a great one, but I never recommended it because it used to need extra configuration steps to work with ASP.NET sites. I think my favorite one is [localtunnel](https://localtunnel.me), which I've used a lot in the past. Best part is that it's both free and open source, so hopefully it won't end up closing down on us.

**Comment by mobbsie** [comment]
It is a bit different in the way it works and requires a bit more initial config, but I have always used DynDns effectively. I think it costs $36 per year for up to 30 host names.

**Comment by nozzlegear** [comment]
Thanks for the recommendation! I think I might have received that one before too, maybe from you? I'm making a list of different services to use that I'll at least recommend as alternatives in the book.

**Comment by mobbsie** [comment]
No problem Josh. I don't think I have ever been in touch with you re: DynDns so must have been someone else. Your handbook is great by the way. Well done and keep up the good work.

**Comment by clement911** [comment]
Thank you for the suggestions. For now, maybe it would be a good idea to simply list those different tools with pros and cons (or just a url and the price) in table in the wiki?
I think we could close that ticket then...

**Comment by ernestogutierrez** [comment]
I've used ngrok for a while, it works great for webhooks and admin embedded apps but I have problems using it with a proxy app and I think it is something with the ssl certificate of ngrok.  If you want to use ngrok with iis express, you should use the host rewrite parameter of ngrok. You can also create .bat files so you can save your configuration for a later use. 

In the last few days I've tried forwardhq.com, it seems to work fine with proxy apps but I'm not 100% sure yet because it only works when I have fiddler opened. The thing I don't like is that everything I close the service and open it again i have to manually choose again the subdomain for remote access and the localhost port. 

So the perfect service for me would be something with this:
- has http and https
- works for webhooks
- works for embedded apps
- works for proxy apps
- it has some way to create and script or config so it "remembers" the subdomain or url to the Internet and the localhost port to use. I use .bat files with ngrok. 

Could we discuss this in a chat or something and after getting the results write a post or add some information to the readme file? I would like to know your thoughts about the different services. 

Thanks.

**Comment by clement911** [comment]
I ended using ngrok, mostly because it seems to be the most popular and I don't have the time to test all tools available.
I had to pay a for a subscription to get a permanent subdomain, but that was under $100 for a whole year...
The docs are ok, but I still had issues configuring the host-header and ssl.
It one of those things that painful to switch, but once it is set up you hopefully don't have to think about it anymore. It's been working fine so far, I will report any issues if I find any...
One thing I do like is that there is a web console where you can see all the requests that were forwarded (including headers) and one can also replay requests (e.g. to test webhooks...).

**Comment by ernestogutierrez** [comment]
To use ngrok with iis express you can use:
` ngrok.exe http -subdomain=mysubdomain -host-header=rewrite localhost:xxxx`
Example:
`ngrok.exe http -subdomain=clementdeveloper -host-header=rewrite localhost:44660`

I haven't had problems with the ssl working with webhooks, and embbeded apps, but it doesn't work with Proxy apps, that's the reason why I also use forwardhq. 

There should be a way to configure ngrok to use a valid certificate or so but it was to painful so I just used forwardhq for proxy apps. But I prefer Ngrok as it's more complete, for example you can create .bat files to just start ngrok with the configuration you want but I haven't found a way with forwardhq.

If you happen to find a way to use Proxy Apps with ngrok it would be pretty useful.

**Comment by clement911** [comment]
Thanks Ernesto, yes that's what I ended up doing but I couldn't run my localhost site on https (same command as the one you pasted but `ngrok tls` instead of `ngrok http`). It's not a big deal...

I don't own any proxy app so I won't be of any help. It seems curious that they don't just work, there must be something special about them...

**Comment by ernestogutierrez** [comment]
I've used https just by using the http command on ngrok, I tried to use the tls command but I didn't get it to work.

So how are you using the tls command with Shopify?

**Comment by clement911** [comment]
Well I'm not using it since I couldn't get it to work. ngrok starts fine though...
Just to clarify, I can access the https ngrok io endpoint but iis express must run on http, not https.
As I said it's not a big deal for me. I used to run iis express on https but I just switched back to http, and that is fine.

**Comment by ernestogutierrez** [comment]
Ok, I understand, yes, you must use IIS Express with http and ngrok creates a tunnel for http and https pointing to the http localhost address.

If I find a way to use Shopify Proxy Apps with ngrok I'll post again.

**Comment by nozzlegear** [comment]
Sorry I haven't kept up with this issue, I've been out sick with bronchitis for a while. I haven't personally tried forwardhq, but I've personally had the most success with localtunnel when compared to ngrok. I'm going to try to get a guide up for ngrok, localtunnel and forwardhq. I'll put it in the book, on my site and here on GitHub when it's ready.
