### ISSUE TITLE
Update methods should accept an id parameter

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#126]
Update methods in 3.0 accept only the object and require that the id be set on that object. In 4.0 devs will be able to send partial objects for updating (#62), so we should change those methods to accept the id and then the object:

```cs
await service.UpdateAsync(objectId, partialObject);
```

**Comment by nozzlegear** [comment]
Implemented in 4.0 branch.

**Comment by clement911** [comment]
I was wondering about this. What if I actually want to set a property to null?

**Comment by nozzlegear** [comment]
That's a good question. Right now it would be impossible to send a null value as null properties are ignored when serializing. Maybe an extra parameter for each create/update method that tells the method to send null values? 

```cs
public async Task<whatever> UpdateAsync(long id, whatever object, bool sendNullValues = false)
{
  ...
}
```

That would bring us back to where we were in 3.0 though, where it's possible to accidentally send along values we didn't mean to.

**Comment by clement911** [comment]
To be clear I haven't encountered that scenario, but I think it is a valid one.
The issue is that you may not always know if your code did set a property to a null, because it may be dynamic... So you would always need to pass sendNullValues = true in that case.
Not to take us a step back or anything, but I had suggested a solution a while back that still seems pretty good to me: https://github.com/nozzlegear/ShopifySharp/issues/62#issuecomment-239722771
It would be a bit more work for the library to change every setter... Maybe something to think about...
