### ISSUE TITLE
ShopifyMetaFieldFilter - Description property

### ISSUE THREAD

**Issue by Saquibadil** [nozzlegear/ShopifySharp#132]
Is it possible to add Description Property in the ShopifyMetaFieldFilter.

Thanks

**Comment by nozzlegear** [comment]
Hey @Saquibadil, I'm hesitant to add properties and functionality that isn't officially documented by Shopify, just because they might stop working at any time. The `Description` property on a MetaField filter is one of those undocumented properties. However, I do have some ideas for letting devs do this without officially supporting it. The first idea would be to extend the ShopifyMetaFieldFilter and add your own properties:

```cs
public class MyCustomMetaFieldFilter : ShopifyMetaFieldFilter
{
  [JsonProperty("description")]
  public string Description { get; set; }
}
```

I haven't tested that yet, but I *think* it should work. I'll try it myself later today and report back here.

**Comment by Saquibadil** [comment]
Good Idea. I will try doing that.
Can you direct me to officially documented list of properties that will work for MetaField filter.
It's not easy to find on google.

Thank you!

**Comment by nozzlegear** [comment]
No problem! [The API reference for MetaFields](https://help.shopify.com/api/reference/metafield#index) has them listed. The filter properties are the ones that are documented for sending with `get` requests.

![image](https://cloud.githubusercontent.com/assets/2417276/25438289/9594d9e4-2a5e-11e7-9e0e-b7530f1ba585.png)
