### ISSUE TITLE
Remove metafields property from all objects.

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#135]
Some objects have a `MetaFields` property that is only used when creating or updating the object. It's never returned by Shopify because they're supposed to be accessed by the MetaField API. However, some `CreateAsync` and `UpdateAsync` calls *can* actually send along MetaFields to the object. If we end up keeping those, they'll probably be moved to overloads on the supported methods.

This is a breaking change, so it's scheduled for v4.

**Comment by clement911** [comment]
Oh I see, so there is 2 different was of writing metafields? Either through the entity service or the metafield service? Pretty weird.
I guess you could make the same argument for any write-only properties...

**Comment by nozzlegear** [comment]
Yep that's right, you're supposed to use the MetaField API to work with MetaFields, but some endpoints also let you send along MetaFields when creating or updating. They're never returned by any other endpoint though, so it's confusing to have them on the objects themselves.

**Comment by nozzlegear** [comment]
Implemented in 6d0cdba

**Comment by MisinformedDNA** [comment]
I'm new here, but I disagree with this change. 

It shouldn't matter that the property is only used for creates and updates. Better documentation would have cleared up any confusion.

I care because my company is looking into connecting hundreds of products into Shopify. Due to Shopify's API rate limits, being able to add as much as possible in a single call is really helpful. I found this change looking for a solution, but instead, I find that the solution was removed.

And unless I'm mistaken, there is no other way to bulk create metafields.

Disappointing.
