### ISSUE TITLE
v4 migration?

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#140]
Hi @nozzlegear

I haven't followed your efforts on v4 but if I understand correctly you're working pretty hard on it!
Could you please elaborate a bit on the timeline and migration path you have in mind?

For example at the moment I'm thinking of enhancing v3 to add support for abandoned checkouts.
But it's not clear to me, whether all functionality in v3 will be available in v4 or if it is a re-write?
Maybe I should wait?

Thanks

**Comment by nozzlegear** [comment]
Hey @clement911, good question! I'm pretty close to getting v4 published, I've only got two or three big tasks left for it. I'm hesitant to give an exact timeline because I'm not great at sticking to them. 😉 Right now I'd estimate maybe 3-5 weeks until everything is ironed out and the next major version is published. It'd probably be best to save any more changes for v4 at this point, but I'm still happy to accept pull requests and convert them myself if you need the functionality right now.

**Comment by clement911** [comment]
I see.
Are you aiming to have feature parity with v3 when v4 launches?
5 weeks may be a bit long but if you can't convert Abandoned checkouts to v4 I can always do it myself later on...

**Comment by alectec** [comment]
Hi @nozzlegear and @clement911 - I just picked up the abandoned cart entity again.  I started a while back but became very busy.  I'm hoping to finish over the holiday weekend.

**Comment by nozzlegear** [comment]
Good to hear @alectec! I think @mobbsie would be interested in that too, looks like the Abandoned Checkouts API is pretty popular!

@clement911 I'm going to take a crack at getting #62 finished this weekend, or as close to finished as I can. That's the only major work left, after that everything that remains should be finished relatively quickly.

**Comment by clement911** [comment]
Thanks, no rush for me personally I'm not sure when I'll be able to migrate to v4, depending on upgrade path...

**Comment by mobbsie** [comment]
Hi @alectec. That is great news. How can I help? I really need to get Abandoned Cart functionality in my app but have also been distracted by busyness.

**Comment by nozzlegear** [comment]
I just realized I didn't answer your question about parity @clement911. All of the services will keep the methods they have, but some params have been changed, e.g. all Update methods now look like `UpdateAsync(long id, ClassName objectToUpdate)`, where before they didn't take an `id` param. The RequestEngine has been removed (instead all services extend a BaseService), so the RequestEngine's retry policies have been moved to that BaseService. You'll also be able to set a retry policy for an individual instance instead of globally. 

The biggest change will probably come from making all properties nullable as discussed in #62, and removing the Shopify prefixes from all classes and services. So, there will definitely be some work involved to upgrade to version 4 of ShopifySharp, but hopefully not *too* much.

**Comment by clement911** [comment]
Thanks! That sounds like a pretty easy upgrade path...

**Comment by alectec** [comment]
@mobbsie I can check-in what I've already completed and we can divide up the remaining items such as unit tests.  Does that work?

**Comment by mobbsie** [comment]
@alectec That sounds great. I presume you will check-in to your own fork for now?

**Comment by alectec** [comment]
@mobbsie Yes, I'll just checkin to my own fork.  I should be able to do that this evening and we can work together to finish.  Thanks!

**Comment by mobbsie** [comment]
Excellent, thanks @alectec.  I will fork your repository now and then update when you have committed the changes.

**Comment by alectec** [comment]
@mobbsie I finally got around to reviewing what I started on the abandoned checkout.  The entity is complete and the service is mostly.  I'll give you a full rundown once I clean it up a little.  I'll be checking into my fork late tonight.

**Comment by alectec** [comment]
@mobbsie @nozzlegear I checked in what was completed previously for abandoned checkouts.  The entity and service is there but needs the test stubs filled out and properly tested.  Please review and send me any questions.  If you end up finishing it, I will plan to move onto another unimplemented part of the API.

**Comment by mobbsie** [comment]
Thanks @alectec.  I have downloaded the latest version and will start testing it asap.  I have a few urgent commitments this week but will revert when I have had a chance to play.

**Comment by alectec** [comment]
@mobbsie Hello.  I was wondering if you had a chance to finish the abandoned checkouts yet?  I was planning to start another set of missing entities.  Let me know if you need help!

**Comment by mobbsie** [comment]
Hi @alectec. Yes, I have managed to get it working but we have a new arrival in our house so I just haven't had the time to commit it all yet.  I had to make a number of changes to get it working as I needed it to so I want to commit it with adequate notes so that you can decide what to keep and what to discard. I will try find the time this coming week to upload it all. Have a good weekend.

**Comment by alectec** [comment]
@mobbsie  Congrats on your new arrival! Whenever you get to it is fine.  I'll move on to the other entities.  Have a great weekend!

**Comment by mobbsie** [comment]
Hi @alectec,

Just to let you know that I have submitted a pull request for the changes I made to your code for the Abandoned Checkout directly to @nozzlegear as your repository seems to be quite out of date and I didn't want to submit a whole bunch of changes which weren't relevant to the code changes I made.  Hopefully you can pull the update from the core @nozzlegear  repository when he has accepted the pull request.

Have a good end to the weekend.
