### ISSUE TITLE
List all tags

### ISSUE THREAD

**Issue by olexandrman** [nozzlegear/ShopifySharp#147]
How can I get a list of all tags from all products through the Shopify Sharp API?

**Comment by nozzlegear** [comment]
Hey, as far as I know there's no direct API call to get a list of tags from a Shopify store. The quickest way I can think to do this would be to loop through all products on the store and just push the tags to an array, but some caution is advised because there are shops out there with tens of thousands of products. Luckily we can use the List call and the `Fields` filter to only return a product's `Tags` property.

It would look something like this:

```cs
var tags = new List<string>();
var service = new ShopifyProductService(url, accessToken);
int totalProducts = await service.CountAsync();
int productsPerPage = 250; // Max is 250, default is 50
int totalPages = (totalProducts / productsPerPage) + (totalProducts % productsPerPage == 0 ? 0 : 1);

// Keep listing products until we've got them all
for (int i = 0; i <= totalPages; i++) 
{
    var products = await service.ListAsync(new ShopifyProductFilter() 
    {
        Limit = productsPerPage, // Max is 250, default is 50
        Fields = "id,tags" //Only pull in the Id and Tags fields (must match the raw JSON property name)
    });

    // Add the product tags to the master list
    tags.AddRange(products.Select(p => p.Tags));
}
```

That should get you most of the way there. Only thing you'll need to look out for is hitting the API rate limit when a shop has thousands of products. You can use one of the built-in retry policies – e.g. `ShopifySharp.RequestEngine.SetExecutionPolicy(new RetryExecutionPolicy())` – or add a try/catch around the `service.ListAsync` call and use it to catch `ShopifyRateLimitException`.

**Comment by pveilleux** [comment]
Using this code I get the first page of products twice. I can see that you loop from page 0 to the number of pages. I was wondering if there is a reason for that? According to the Shopify API documentation the default page number is 1. I did some tests and when I call the API using page 0 or 1, I get the same list of products for both of them.

`for (int page = 0; page <= totalPages; page++) `

Let's say I have 1 page of products, they will be returned twice using this code.

**Comment by nozzlegear** [comment]
@pveilleux Good point! The page should in fact start at 1 or else you'll get the first page twice. I'm too used to starting indexes and loops at 0. 😜

**Comment by pveilleux** [comment]
That's what I thought :) Thanks for the confirmation. I usually do the same when dealing with indexes :)
