### ISSUE TITLE
ShopifyTransaction.Amount shouldn't be nullable

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#148]
Any reason ShopifyTransaction.Amount is nullable?

**Comment by nozzlegear** [comment]
It's been so long since it was written, I can't remember why it was nullable. I assume I ran into a null value when I was testing, or maybe it was just copied from a different class. I'm not super keen on changing this right now though, as it will just be reverted in v4 where *all* of the properties will be nullable, even if it probably doesn't make sense in some cases like this one.

**Comment by clement911** [comment]
For an order, I guess I can see why it is nullable, so that one can do a partial update of an order. Indeed the id is not needed since it is already specified on the url (PUT /admin/orders/#{id}.json).
Do you remember if that was the reason?
Since Transactions cannot be updated, I guess it should always be non null, but I guess for consistency with other entities it can be argued it should be nullable too...

**Comment by nozzlegear** [comment]
I don't think that was the reason, but it does certainly help for doing partial updates. It really shouldn't be nullable, but I think for my own sanity and for consistency with the rest of the entities in v4, I think it'd be better to leave it as nullable. It shouldn't do any damage that way beyond making developers add an extra `.Value` when they want to use the property.
