### ISSUE TITLE
Odd behavior with webhook creation

### ISSUE THREAD

**Issue by speranza134** [nozzlegear/ShopifySharp#187]
So I am able to successfully create webhook and using the ShopifySharp library I can list it as well. However, when i navigate to <my.shop.url>/admin/webhooks.json the list is always empty. 
I am quite stumped as the webhook service seems to call the same api as well and it lists the created webhook for me.
The webhook in question is AppUninstall. It doesn't seem to work. Any ideas?

**Comment by clement911** [comment]
That is because the webhooks service is 'scoped' so that it returns only the webhooks of the current app.
This is so that you can't interfere with other apps webhooks. When you simply navigate to the page, there is no app context so I think it only shows the webhooks that you manually register in the admin.

**Comment by nozzlegear** [comment]
Yes, @clement911 has it exactly right. The webhook list shown in the admin page only shows webhook that were created by the admin dashboard, it won't show any webhooks created by an app.

**Comment by speranza134** [comment]
So how do I get the install webhook to work? I have followed the example in the AuntieERP sample project but it doesn't seem to work. It's not throwing any errors as well. The webhook is created but not used when the app is uninstalled.

**Comment by nozzlegear** [comment]
Debugging webbooks can be somewhat difficult, it's one of my biggest pain points when building Shopify apps. The first step is to make sure a request is even coming though to your app.  You'll have to test this manually by installing the app on your Shopify Store , and then uninstall it manually too. (Make sure you're using a localhost forwarding service like Ngrok.io otherwise those requests won't reach your test machine). Use visual studio's debug mode and set a breakpoint in your web hook handler to see if it's even being hit.

**Comment by speranza134** [comment]
Sorryi haven't been able to respond earlier. was a bit tied up. I have been putting loads of debug messages to return as content string around this webhook and publishing on a server and I can definitely see it creates the webhook. It just fails to hit the uninstall webhook controller when i uninstall the app from store. Am i missing something here?

**Comment by dthpth** [comment]
@speranza134, keep in mind that right after the app uninstalled all auth tokens obtained with it's public key for that store become invalid. So if you are trying to access the customer's shop in AppUninstall hook code you will get 401 error.

Also, you could use some public url-inspectors (like https://requestb.in/) to make sure that shopify hits it when app uninstalled.

Hope it helps.

**Comment by speranza134** [comment]
Ok I'll give that a go and keep you posted with the outcome here. Thanks.
