### ISSUE TITLE
Create a ShopifySharp.Strings package

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#244]
I'd like to get the functionality we used to have with enums back, but I don't want it tied to this package and require an update each time they change. Somebody had suggested using constant strings, which I think is a great solution. This way the functions in ShopifySharp itself can continue accepting strings, and developers can easily update their own app when something changes, but we can also have a set of "known" values that can be updated separately. 

```cs
public static class WebhookTopics 
{
  public static const whatever string AppUninstalled = "app/uninstalled";
}
```

**Comment by clement911** [comment]
Sounds good to me. Although, what's your thinking around putting this in a separate package?

**Comment by nozzlegear** [comment]
Just to let us push updates more quickly when there are new string constants added or some removed. If it's in it's own package devs can more safely update to get the latest values without having to deal with changes from the main package.




--


Josh Harms







On Fri, May 11, 2018 at 8:03 PM -0500, "Clement Gutel" <notifications@github.com> wrote:












Sounds good to me. Although, what's your thinking around putting this in a separate package?

**Comment by clement911** [comment]
Right. I thought it was something along those lines, but in theory if the strings were in the same packages, adding strings should not be breaking change..

**Comment by nozzlegear** [comment]
Oh yes, sorry, I meant it would let people stay on 4.x for example and they wouldn't have to upgrade to 5.x just because strings change.




--


Josh Harms







On Fri, May 11, 2018 at 8:29 PM -0500, "Clement Gutel" <notifications@github.com> wrote:












Right. I thought it was something along those lines, but in theory if the strings were in the same packages, adding strings should not be breaking change..

**Comment by clement911** [comment]
Got you.

**Comment by davron12** [comment]
Fairly new to Shopify, so this may be a naive question, but how often does Shopify add new webhooks/constants? If it's very often, then a separate package makes sense. If it's about as often as they add new services, then you may want to keep it in the same package. The theory being, if you need the new constants, you probably also need the updated service and entity classes.

**Comment by nozzlegear** [comment]
*Almost* every service has some kind of enum somewhere. The enum converter worked well for a while, but the problem is Shopify does not always document every value or change, so when an "enum" comes in that can't be matched up with a known enum it will either throw an exception or be null. It was something we struggled with through versions 1 and 2; it was such a big problem that eventually I just said screw it and ripped the enums out, replacing them with strings.

Since they're strings now, we can add string constants so developers relying on the package can quickly update their own app with new string values when something changes, instead of waiting for a new ShopifySharp release. And if the strings are in an entirely separate package, they won't be forced to update from e.g. ShopifySharp v4.x to ShopifySharp v5.x to get the latest string values.

**Comment by davron12** [comment]
I'm more the string approach but not a separate library. Developers that want to use an new code that's not available can hard-code the string into their code. Keeping it all in one package gently nudges developers to upgrade their code to the latest version, while not requiring them (because you made it a string).

**Comment by dkershner6** [comment]
Agree with @davron. It's highly related, and someone could fork if they really just want the strings part.

**Comment by Kirlac** [comment]
Although @davron12 makes a good point about nudging devs to update their dependencies, unfortunately that's not always how things work. It's one thing if you stay in the same major/minor eg. going from `4.15.x->4.16.0->4.16.1` - assuming the library is accurately using semver this is a relatively unimpactful change so update away. Going from `4.x->5.x` on the other hand is a far riskier move for a production system and major updates like these will often get deferred due to developmental resource constraints

On the other hand, having separate packages does offer some benefit:

- The core package will be more light weight as it doesn't contain these. If you don't need them or only need a very small subset of them you can replace the strings package with something else eg. a small class with only the few strings you need or even a custom 3rd party extension package (which could then potentially offer something like a conversion service layer giving some of the type-safety constraints of using enums and mapping those up to strings for the client services to use)

- Some minor string changes will no longer necessitate a full package update for the consumer (as mentioned earlier, this is more critical when updating to a new major). It will also work the other way around - the core package can then be updated without having to also update the strings if you don't need the updated versions eg. shopify adds a new api that you don't need, but the core version has a bugfix you do

- It makes developing and maintaining the package easier by reducing the need to backport these changes into an older version AND the add them to the current development version (for example releasing `4.16.2` with some string changes and also having to synchronize those changes with the `5.0.0-pre` currently in development or vice versa). As a separate package you can just update the strings package itself and all versions can use the same source for the strings without having to update the core/service package versions - less maintenance ftw!

Overall, I like the idea of separating the packages and it does seem to be a common theme for a library to consist of a few packages in the dotnet ecosystem right now - especially around dotnet core - eg. [`Geocoding.Net`](https://github.com/chadly/Geocoding.net) became `Geocoding.Core` and `Geocoding.Google`, `Geocoding.MapQuest`, `Geocoding.Microsoft` & `Geocoding.Yahoo` all as separate packages - granted these sub-packages contain more than just string consts/models, but the concept is valid

**Comment by nozzlegear** [comment]
At the moment I think I'm going to close this simply because I haven't had the time to do it myself and get by decently well just by making my own constant strings class for the strings I'm going to use in a project. If anyone wants to contribute this I'd be happy to merge a pull request!
