### ISSUE TITLE
Shopify forcing TLS 1.2 - Important!

### ISSUE THREAD

**Issue by noamberda** [nozzlegear/ShopifySharp#267]
Hi,
We have an issue in the past few days with the connectivity to Shopify. The connection keep drooping some times.

I noticed the following on shopify
https://help.shopify.com/manual/your-account/account-security/tls

Shopify upgraded to version 1.2 and i think that causing the problem. What strange is that we get the error only sometimes.

We had similar issue with Zendesk API and we had to add the following line before each HTTPS client cal
//specify to use TLS 1.2 as default connection
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

https://stackoverflow.com/questions/22251689/make-https-call-using-httpclient/22251844

Can you guys check it as well? I think the line need to be added.

Noam

**Comment by nozzlegear** [comment]
Thanks for creating this issue! There was another one recently discussing the same thing, and I ended up adding a warning to the readme about this. I'm wondering now if we should just enable it directly in ShopifySharp, though I believe that will automatically set it for a user's entire application. @clement911 any thoughts on this?

**Comment by clement911** [comment]
Shopify had reverted their change and reapplied it on June 20th. https://ecommerce.shopify.com/c/api-announcements/t/shopify-is-deprecating-its-support-of-tls-1-0-and-1-1-517130

It's tempting to set `System.Net.ServicePointManager.SecurityProtocol` from ShopifySharp but at the same time it doesn't feel right to set a global variable from a library, as it could have other unintended consequences.

Maybe the `ShopifyService` could check the value and throw an exception with a good error message if it detects the current value won't work?

**Comment by davron12** [comment]
I just spent a couple hours trying to figure out what was wrong with some new code I had written. Since it was new code, and not old code that just stopped working, I figured I was doing something incorrectly. Well, I was, I had forgotten to set the SecurityProtocol, but none of the errors suggested that.

I agree with @clement911, ShopifySharp shouldn't set the SecurityProtocol, but it would be great to throw an exception with a warning about TLS, as the current exception's message is "An error occurred while sending the request", which is totally useless.

**Comment by nozzlegear** [comment]
I'm a little torn on throwing an exception as soon as we detect the security protocol. I'm wondering if there's a way to check that the exception thrown when making a request is due to TLS, and then write a more useful error message detailing how to fix it.
