### ISSUE TITLE
Split the model from the authentication parts

### ISSUE THREAD

**Issue by TOuhrouche** [nozzlegear/ShopifySharp#278]
It would be really nice if one could split up the solution and the nuget package into two parts:
- The model part which contains all the business domain objects such as Product, Order, Location... 
- Authentication and authorization part. 

The split would allow usage of the models without the need to pull in all the HTTP and Web related packages wherever the library is used.

**Comment by nozzlegear** [comment]
Thanks for suggesting this! To be honest, I lean toward keeping authorization and authentication in the main package since it's a huge part of creating a Shopify app. I'm not sure I see the advantage for splitting them. If this were done and the models were split into their own package, do you envision that package containing the "services" too so that you could make requests to the Shopify API with those models, or would you just be working with JSON in that scenario?

**Comment by TOuhrouche** [comment]
Hey! Thanks for the quick reply. These packages are very likely to be used in applications where the architecture is decomposed into two parts: 
1. The first part would be the front end where the users will initiate the OAuth flows and so on. 
2. The second part is long running cron job processing orders and data sent over to Shopify. The second part doesn't require the OAuth code, libraries and all the dependencies this part pulls in. 

I hope this make sense.
