### ISSUE TITLE
Run tests inside a Docker container

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#327]
Running inside a Docker container lets me easily pass a .env file to the test suite, and makes the builds/tests reproducible.

**Comment by dkershner6** [comment]
Are you suggesting like an ongoing Docker container that is always testing?

If not, I guess I dont see the difference between using a local.settings.json or appsettings.development.json for this purpose, vs a Dockerfile/env file.

It would be nice to have some sort of public, testing store that we could all use for testing as we make changes, but I dont think I'd want to publicly expose credentials, and dont blame you for feeling the same.

**Comment by nozzlegear** [comment]
Not one that's ongoing and always testing, but just one that I could do `docker run --env-file file` to run tests. A json file would work too! I guess I haven't investigated using them, I kinda thought they were an ASPNET-only thing. 

I agree it would be awesome to have something public that everyone could use for tests, but like you said, I don't want to expose credentials. I do have automated testing set up for the master branch already though, and it runs before I release anything. One "nice to have" thing I've been thinking about is setting up a bot that I can give commands to from a pull request, to make it run certain tests before I merge a PR.

**Comment by dkershner6** [comment]
They are primarily ASPNet or Azure Functions used, but you can also just digest a file in a class library (old school File.IO, thats how those do it anyway)

You can add that file to your .gitignore so it doesnt get uploaded to us, and load the file in the testing library as variables used in tests.  The tests wont work without the file, obviously, but it would work on your dev machine, or for another dev who has your file, or creates a new one.

This is a set up I use (primarily in those areas above) for integration testing (testing outside the library, AKA Shopify) frequently.  It is much easier and quicker than launching docker, as it runs within VS on the fly in the typical unit testing environment.  You can also upload your variable file to a Continuous Integration/Deployment environment, and have it run the tests there too if you like.

Just advice though, your idea would very much work as well if you so chose, but keep in mind that whatever was inside the docker would need to be executable (not just a xUnit library, maybe a console app?)

**Comment by nozzlegear** [comment]
While I'm thinking about this, I had an idea and would love to hear your feedback as someone who's actively using the package. (I'm using it too but would like someone else's perspective). Is it important to you that the package is making calls to the Shopify API and actually creating/updating/deleting objects? Would you have less faith in the package if the unit tests were reworked to just verify that the URLs being called are correct, and that the objects being serialized/deserialized are correct? 

The reason I'm considering such a change is that the package is making tons and tons of calls to the API every time a change is merged into master. It takes a long time to run the tests because it's dealing with the retry policies and rate limits. There have also been several times where tests just break and I have to disable them because I either can't figure out _why_ they broke, or because Shopify broke them on purpose (such as limiting the number of fulfillments on dev stores). Going further, I can't even test the Shopify Plus APIs -- I've contacted my Shopify partner manager several times about getting Plus access just for testing this package but they won't do it.

To be clear, the way tests are running right now _does_ work. But since it requires a private app with all permissions just to run tests, it takes some effort to get the package set up to run tests on your own machine; I imagine most devs creating pull requests are _not_ running tests. 

@clement911 It'd be great to have your feedback here too.

**Comment by mclarenengineering** [comment]
Let those it work

**Comment by dkershner6** [comment]
Integration tests are great in theory, because a change to Shopify's API would never be caught by any other type of test.  That being said, each one of our apps is essentially a constantly running integration test (so long as we all have monitoring), so I'd suggest the chances of the integration tests catching something first are pretty small.

I guess my question to you is, how many times have the integration tests caught something that you wouldn't have otherwise caught?  1/1000, I'd say keep em running.  1/1000000, I'd say their value is limited, and sound like they cause you more headache than they're worth.

**Comment by clement911** [comment]
I don't have a super strong opinion on this.
I'd have better confidence when integration tests pass rather than just serialization tests because obviously they are testing more, but I also agree that integration tests can be slow and brittle.

You said you didn't want to expose credentials but what is the worst that can happen if we were to embed real credentials in the repo to an actual dev store? We could create a dummy shopify partner account specifically for ShopifySharp integration testing. I guess someone could mess with the dev stores but not sure why anone would bother...
Shopify did actually enable Plus APIs on my dev stores (users, gift card), so maybe you just talked to the wrong person.

If the tests encounter limits imposed on dev stores (such as limiting the number of fulfillments on dev stores), I would say simply ignore/delete these tests.
As far as tests where you can't figure out why they fail, is there no error messages? or are they just too criptic / you don't have time to investigate?

**Comment by dkershner6** [comment]
> I guess someone could mess with the dev stores but not sure why anone would bother...

I have learned to stop asking this question of people on the internet, and assume they, indeed, will bother.

**Comment by clement911** [comment]
Sure, someone could. does it even matter?

**Comment by dkershner6** [comment]
The only possible problem I could foresee is that Shopify partner program people get mad at @nozzlegear for spamming the API...or something.

I do agree the risk is low, but im not sure it's low enough to call it zero.

**Comment by dkershner6** [comment]
I thought about this a little more, I think the biggest risk would be someone uploading malware or something illegal and then linking to it.
