### ISSUE TITLE
.net core Demo Project timeline?

### ISSUE THREAD

**Issue by dementic** [nozzlegear/ShopifySharp#346]
Is there an estimate on when a demo project will be available?

**Comment by dkershner6** [comment]
This is a pretty simple library with very large documentation, is there something you feel is missing?

.net core is the same as framework here.

**Comment by dementic** [comment]
Yes, a Demo project that is using the .net Core version.
The only Demo project available at the moment is using .net 4.5

**Comment by dkershner6** [comment]
There is no difference between using the library in .net core 2.1 and .net 4.5, so the benefit of this would be very small.

Since I am one of the few contributors using .net core, this would likely fall to me, and because of next to no benefit for a medium amount of work, I would suggest there are no plans to create this until .net core outpaces framework usage or something becomes specific to using .net core.

@nozzlegear or @clement911 - feel free to close this one up unless you disagree.

**Comment by dementic** [comment]
This will contradict The Email and Book which clearly states ".net core demo project will be created soon".
But oh well, i already did myself anyway.

**Comment by dkershner6** [comment]
Great!  Go ahead and drop a link to it here and we will check it out.

**Comment by nozzlegear** [comment]
Hey, I _am_ working on a .NET core starter project, but it's for that email list and the people who've purchased my book. It won't be an "official" part of this package or repo.

**Comment by dkershner6** [comment]
Fair enough @nozzlegear - stand corrected.

**Comment by dkershner6** [comment]
Oooooh, now I see.  This is someone asking about your book and such which USES ShopifySharp.  I can see how it would be easy to use this as a place to ask questions about that I suppose.  Apologies for not realizing this (and therefore replying with confusion).

**Comment by nozzlegear** [comment]
Haha that's alright! I really need to set up some separate place to file issues or ask questions about the book.
