### ISSUE TITLE
.NET 4.5 Incomplete Requests

### ISSUE THREAD

**Issue by farlee2121** [nozzlegear/ShopifySharp#347]
I'm trying to make calls from ASP.NET MVC 5 (version 5.2.3) and .NET 4.5. However, when I call into a service, it never completes. 

Debugging Behavior: The service instantiates fine. When I step over a remote call, i.e. `ShopService.GetAsync(...).Result`, the debugger never reaches the next line. The containing controller call never completes.

I know that all of my arguments are valid. The exact same apikey, secret, access token, and shop work from postman. I have also successfully made the same calls by building the request myself with HttpClient. I also properly set the default TLS versions.

So far, I know this behavior happens with 
  - AuthorizationService.Authorize
  - ChargeService.CreateAsync
  - ChargeService.ActivateAsync
  - ShopService.GetAsync

The url built by AuthorizationService.BuildAuthorizationUrl does work properly though.

Any ideas?

**Comment by nozzlegear** [comment]
Hey @farlee2121, I'm pretty sure this is because all of the ShopifySharp methods are asynchronous but it looks like you aren't awaiting them. I do see you're using `GetAsync(...).Result` which sometimes works, but in general should be avoided since it can result in deadlocks like you're experiencing. Since you're using ASP.NET it should hopefully be easy to convert to async/await, you'd just need to make your calling method async -- if it's a controller action, that will be super simple:

```cs
public class MyController : Controller
{
    public async Task<IActionResult> Index()
    {
        var service = new ShopService(...);
        var shop = await service.GetAsync();

		return View();
    }
}
```

The key part is to mark your method with `async` and then use `await` on any asynchronous method inside of it.

**Comment by farlee2121** [comment]
It seems I was mistaken in thinking that Task.Result was equivalent to awaiting. This has solved the deadlocking issue. It might be good to note this along-side the TLS issue. It isn't super obvious and can undermine usability.

Thanks for the quick support!

**Comment by nozzlegear** [comment]
Good idea, I'll add a note to the docs this weekend!
