### ISSUE TITLE
Update Order Class

### ISSUE THREAD

**Issue by mahrukhgull** [nozzlegear/ShopifySharp#364]
Add Order.Test
Add Order.Confirmed
Add Order.reference
Add Order.ShippingLines.DeliveryCategory

Thanks

**Comment by nozzlegear** [comment]
Hey @mahrukhgull! Thanks for reporting this. The package does support the `Order.Test` property already. However, the `Order.Confirmed`, `Order.Reference` and `Order.ShippingLines.DeliveryCategory` are not officially documented by Shopify, which means they may be new properties that will be added/documented in the future, or they're old properties that will be removed. Currently this package's policy is to only support properties and APIs that are officially documented ([which would be here](https://help.shopify.com/en/api/reference/orders/order)), so sadly I can't add these extra properties at this time.

**Comment by clement911** [comment]
Here is quick thought.
It could be useful if the API allowed the user to provide their own generic type parameter.
This way if I really wanted to add unsupported properties I could inherit from Order and call `ListAsync<MyOrder>` and instead of the default `ListAsync<Order>`
I thought we could do that already so maybe I'm missing something..
