### ISSUE TITLE
Add a retry policy to keep retrying until arbitrary function returns true

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#371]
```cs
var service = new ProductService(...);
service.SetExecutionPolicy(new NameTbdRetryPolicy(failures => failures < 20));
```

**Comment by dkershner6** [comment]
For your actual specified case, I think you'd be better off adding a max retries to the smart execution policy or just running the query in a for loop.

If you mean more like based on the product data, like a while loop, I think this may have done merit, but I would see it more as an extension method of the getasync method, or an option.

**Comment by nozzlegear** [comment]
More like a while loop is what I had in mind, the max retries example was just the first example I could think of off the top of my head. I think I don't quite understand what you mean by making it an extension method or an option though, could you explain that a little bit?

**Comment by clement911** [comment]
What's the use case for this?

> For your actual specified case, I think you'd be better off adding a max retries to the smart execution policy or just running the query in a for loop.

I think it'd be a better fit for the simple ```RetryExecutionPolicy``` because the smart one is designed to implement the leaky bucket policy.
It could be easily extended to also implement an exponential backoff (that waits longer and longer each time it fails rather than waiting for a constant time every time).

**Comment by dkershner6** [comment]
@clement911 , didn't even know that existed, clearly a better fit 

@nozzlegear , my thought is in order to integrate entity data, you will need to know the entity. I.E. if you want to keep calling until variants.count > 3, you will need to know you are looking at a product object or a list of variants. Creating the lambda on the service is too object agnostic (could be a list, an object, or nothing depending on what you call).
