### ISSUE TITLE
Execution Policy Question

### ISSUE THREAD

**Issue by lantram** [nozzlegear/ShopifySharp#399]
Before I release my new app, I'm wondering which execution policy is the best choice?

My app performs bulk processes. I figure it will have hundreds or thousands of users, any of which that initiate events causing thousands of Shopify API calls in succession.

The most important issue to me is overall 1) stability, and 2) speed.

That given, I'm just wondering if there is really any difference or benefit between RetryExecutionPolicy and SmartRetryExecutionPolicy?

And, should I be choosing one over the other? Or does it not matter?

Thanks for any info!

**Comment by clement911** [comment]
SmartRetryExecutionPolicy tracks the leaky bucket level and waits before issuing requests (if needed) rather than blinding sending the request and retrying when it fails.
It means you process ends up issuing less requests, which will almost always succeed (or at least not fail because of an API limit). So it consumes less resources, which can improve scalability.

I think a good pattern is ensuring that only one instance can use any given Shopify access token, otherwise different instances will compete for the same token and tripping each other as they share the same limit.

**Comment by nozzlegear** [comment]
I would agree, the SmartRetryExecutionPolicy is what I use in most production applications. Sometimes I go with a the "dumb" retry policy that doesn't track the leaky bucket level, but that's only in special cases.
