### ISSUE TITLE
Parameters, Interfaces, and ExecutionPolicy

### ISSUE THREAD

**Issue by v-dev-1** [nozzlegear/ShopifySharp#401]
Hi there! 

I have several questions about the current implementation. Why do we need to pass myShopifyUrl and Token to the constructor instead of passing them to each method?

Current implementation:

var customCollectionService = new CustomCollectionService(user.Shop, user.Token);
var response = await customCollectionService.CreateAsync(customCollection);

vs

var customCollectionService = new CustomCollectionService();
var response = await customCollectionService.CreateAsync(user.Shop, user.Token, customCollection);

In addition, it is better to add Interfaces because it will be easier to pass them to other services and use dependency injection:

public interface ICustomCollectionService{
  Task<IEnumerable<CustomCollection>> ListAsync(CustomCollectionFilter filter = null);
  ...
}

public class CustomCollectionService : ICustomCollectionService{
  public CustomCollectionService(){
  ...
  }
}

I also don't like that ProductService, OrderService, etc. include ExecutionPolicy. It is architecturally incorrect that these services know about execution policies. It should be implemented like Polly - https://github.com/App-vNext/Polly

**Comment by nozzlegear** [comment]
Thanks for the feedback! 

I've already got an open issue to add interfaces for exactly the reason you're saying, it will make the package work better with dependency injection and testing. As soon as I've got a chance I'm going to get that completed and merged in. #362 

Regarding passing the shop and token to each method, I can see how that'd be useful but would involve a lot of tedious changes both for myself as the developer of this package, _and_ for all of the developers using this package. If I were to start over, I might have designed the package that way instead, but since we're 4 versions and over 100 releases deep at this point, I don't want to refactor something that already works without a very good reason. 

As for the execution policies, I understand it might be a little architecturally iffy, but there are legitimate use-cases for letting individual services set their own policies. Again, if I could start fresh with what I've learned I would do that, but I'm not going to break everyone's build in pursuit of the perfect design.
