### ISSUE TITLE
Product Create First Call Error

### ISSUE THREAD

**Issue by hltyvz** [nozzlegear/ShopifySharp#423]
Hello, I am getting limit error on first call when creating new product with Api. I'm not getting errors when updating the product. Where am I making a mistake?

Thanks.

Code:
var service = new ProductService(myShopifyUrl, shopAccessToken);
var product = new Product();
***
***
product = await service.CreateAsync(product);

Error:
ShopifyRateLimitException: Error: Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service.

**Comment by nozzlegear** [comment]
Hey, this error means you're making calls to the Shopify API too quickly and you're running into the rate limit. Shopify lets apps make two requests per second, with a burst of up to 40. Most often this happens when you're doing things in a loop. You can either restructure your code to wait between requests when you're looping, or you can use one of ShopifySharp's built-in request execution policies. We usually recommend the SmartRetryExecutionPolicy, which tries to keep track of the requests being sent with the service to prevent hitting the rate limit (this means your requests will slow down if you're making a lot of them). 

--
Josh Harms

**Comment by nozzlegear** [comment]
```cs
var service = new ProductService(...);
service.SetExecutionPolicy(new SmartRetryExecutionPolicy());
```

**Comment by hltyvz** [comment]
Yes, I know about that. But I get the error on the first call. Is it normal for me to get an error on the first call? And I'm using delay in the loop.

**Comment by nozzlegear** [comment]
No it’s not normal to get it on the first call. Are you sure your program isn’t making any other calls to the Shopify API before that product create request? You’re not listing the products, or getting them, or updating them before that call?

--
Josh Harms

**Comment by hltyvz** [comment]
I am sure.  I'm just calling to create the product and getting the Error.  It does not give an error when I call for listing and update. I am still delaying before sending the call to create the product, but it still gives an error.

**Comment by nozzlegear** [comment]
Hmm unfortunately this might be an issue with the Shopify API then and is probably worth sending an email to see if they can investigate it. The error message being returned isn't one created by ShopifySharp, it's just reading the message that Shopify sends. I'm happy to look into it more though, just to confirm. If you want to upload a minimal project to Github that reproduces this issue, I can look into it more.
