### ISSUE TITLE
StringExtensions confusing existing extensions and breaking build

### ISSUE THREAD

**Issue by josh-degraw** [nozzlegear/ShopifySharp#425]
I have utilized (among others) the string extensions `StartsWithIgnoreCase`, `EndsWithIgnoreCase`, and `ContainsIgnoreCase` for use in many places in my organizations code. 

Recently after updating this package I got a bunch of errors that it was ambiguous between the existing extensions and those found in the `ShopifySharp.StringExtensions` class.

I would suggest to mark those internal as they are not critical to be exposed as part of this package and can, as I found out, actually cause compilation failures to downstream users.

**Comment by nozzlegear** [comment]
Thanks for the suggestion! I actually ran into this recently myself. It didn't break any builds for me (thankfully), but those extensions should definitely be internal. If this is critical for you, I'd be happy to accept and merge a pull request. Otherwise I'll get it fixed as soon as I have time this week.

**Comment by josh-degraw** [comment]
Submitted #426

**Comment by nozzlegear** [comment]
Thanks! I'll bump the version and publish it soon.

**Comment by josh-degraw** [comment]
Thanks for the quick merge haha!

**Comment by nozzlegear** [comment]
No problem! This has been published in 4.23.0 on Nuget. Thanks for the pull request!
