### ISSUE TITLE
ListAsync is obsolete and ShopifySharp version 5 is not avilable

### ISSUE THREAD

**Issue by HoomanBahreini** [nozzlegear/ShopifySharp#448]
I am getting a lot of warnings in my code:

> This ListAsync method targets a version of Shopify's API which will be deprecated and cease to function in April of 2020. ShopifySharp version 5.0 will be published soon with support for the newer list API. Make sure you update before April of 2020.

It seems like ShopifySharp version 5.0 is not out yet... as a user I am stuck with these warnings, which are making my code really messy... I think it makes a lot more sense to make these methods `[obsolete]` once the new version is out...

**Comment by sitepodmatt** [comment]
Yes, just noticed this, gone back to just using httpclient as too much of a big red warning sign... Appreciate that you're cutting it fine with underlying dependency and a supposed deadline of april 2020 but you don't mark methods deprecate unless you have a replacement.

**Comment by nozzlegear** [comment]
Thanks for the feedback everyone! I understand that it's annoying to have these warnings, but I wanted to be extra sure that as many people as possible are aware of this change before it happens, instead of waking up to broken apps on April 1st. ShopifySharp v5.0 will be published within the next two weeks.

**Comment by HoomanBahreini** [comment]
Hi, please could you confirm when is Shopify Sharp version 5 going to be released?
