### ISSUE TITLE
Auth without redirect url

### ISSUE THREAD

**Issue by LusienGG** [nozzlegear/ShopifySharp#449]
Is it possible to use the standard way of Shopify API authorization? 
API key, pass, and hostname

https://{apikey}:{password}@{hostname}

as far as I looked at the Auth Service there is the only way with a generated token by adding redirect_url from my app but my app is a console app without actions and can`t use any services.

**Comment by nozzlegear** [comment]
Hey @LusienGG, the package does not currently support using the URL scheme like your example. However, it should work even if you don't have an access token and aren't using the oauth/redirect stuff! 

It sounds like you're working on a private app, instead of one you submit to the Shopify app store? If that's the case, you should be able to find a "password" key in your private app's settings. It might also be called a secret key. You can use that in place of the access token and that should let you make calls to the Shopify API with ShopifySharp:

```cs
var service = new OrderService("my-shopify-domain.com", privateAppPasswordHere);
```

**Comment by LusienGG** [comment]
Alright, I understand it is supposed to work. I got an issue when I call any of these async methods in any service execution exits without any exception. I thought it was an auth issue but still trying to figure it out.

**Comment by nozzlegear** [comment]
Could you post some example code that's not working for you? Are you using `await` on the methods, or are you doing something like `service.ListAsync().GetResult()`?

**Comment by LusienGG** [comment]
Changed 
`var task = await service.ListAsync();
var products = taskAwaiter.ToList();`
to
`var taskAwaiter = service.ListAsync().GetAwaiter();
var products taskAwaiter.GetResult()`

and i got some products 

Thank you so much I`ll look around and in some point I could join with contributions to this project.

Case closed!
