### ISSUE TITLE
Cannot read any data after upgrade to 2

### ISSUE THREAD

**Issue by Panksy** [nozzlegear/ShopifySharp#46]
[ArgumentNullException: Array cannot be null.
Parameter name: bytes]
   System.Text.Encoding.GetString(Byte[] bytes) +11445618
   ShopifySharp.RequestEngine.CheckResponseExceptions(IRestResponse response) +242
   ShopifySharp.<ExecuteRequestAsync>d__4`1.MoveNext() +471

Code is:
var pages = await new ShopifyPageService(AuthState.ShopName, AuthState.AccessToken).ListAsync();

**Comment by nozzlegear** [comment]
Thanks for the report! I haven't seen this before, it looks like Shopify is returning a completely empty error response rather than a message that could be decoded. I've just pushed a fix with v2.0.1 that should at least prevent this `ArgumentNullException` and make the lib throw a `ShopifyException` instead that at least will tell you the response received from Shopify. 

As for why you're getting an error from Shopify when trying to list pages, I'm not really sure. I re-ran the tests for the `ShopifyPageService` and they're all passing, so it might help if you load up Fiddler to see what might be going on with your shop.

![tests-passing](https://cloud.githubusercontent.com/assets/2417276/14571452/eabaae9e-030e-11e6-8adc-2d3ca57e0071.png)
