### ISSUE TITLE
How to go about adding a new service

### ISSUE THREAD

**Issue by mark-jeanswhse** [nozzlegear/ShopifySharp#487]
Hi, I want to add a service that is only supported on Shopify API 2020-01. 

> https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentorder?api[version]=2020-01#index-2020-01

How do I go about adding this to my own project? 
I have added: 
- All Required Entities
- FulfillmentOrderService
- FulfillmentOrderListFilter

Getting this message when creating FulfillmentOrderListFilter
![image](https://user-images.githubusercontent.com/47802161/77198819-d08b2600-6a8b-11ea-9505-06ec255eb143.png)

Thanks!

**Comment by nozzlegear** [comment]
You've got it mostly correct, that's exactly how you go about adding a new service. It looks like that error is saying you need to add a constructor that will implement the base ListFilter's public constructor. We don't have to do that for filters built in to this package, I think because the ListFilter's default, no-argument constructor is internal and the built-in filter classes can implicitly access it. 

```cs
public class FulfillmentOrderListFilter : ListFilter<FulfillmentOrder>
{
    public FulfillmentOrderListFilter() : base(pageInfo = null, limit = null, fields = null)
    {

    }

    // Your filter fields here
    // ...
}
```

@clement911 Any thoughts about this? The internal constructor makes it difficult to create your own filter class, but at the same time we want to guide devs away from trying to use `new ListFilter<T>()`. Can we make the no-argument constructor for ListFilter protected instead of internal?

**Comment by clement911** [comment]
> Can we make the no-argument constructor for ListFilter protected instead of internal?

That sounds fine to me.

Alternatively we could change existing filters so that they never inherit from` ListFilter<T>` (make it sealed) and only use `ListFilter<T>` for paging.
Because it is quite weird that non paging filters can theortically set `PageInfo`.
That would require adding explicitly the `Limit` and `Fields` properties to all the list filters classes though, or I suppose we could create another base class.
Probably what you suggested is just the simplest solution though..

**Comment by drovani** [comment]
Instead of propagating `Limit` and `Fields` properties, what about making a non-generic base class of `ListFilter`. Have all class-specific filters inherit from that as well as `ListFilter<T>` inherit from it. Perhaps at that point, think about changing `ListFilter<T>` to be more liked `PagedListFilter<T>` or something that indicates that it is just for use with paging.

This Shopify change really made a mess of lots of things, didn't it.
