### ISSUE TITLE
Question concerning Updating products

### ISSUE THREAD

**Issue by crestwoodCoder** [nozzlegear/ShopifySharp#49]
I'm sure this is the wrong place to ask questions, but I couldn't find anywhere else. 

I am wondering if its possible to update products with some minimum information without first retrieving the full product.  For example, if I store the ProductId and I just want to update some conditional fields (almost all of them in a variant - the quantity and prices), is it possible to use your library to update that product without first reading the product (thus consuming 2 API calls).  

If it is, can you please tell me how this can be done ?

**Comment by Infob** [comment]
As long as you have the productId, only one call (PUT) is required. The Shopifiy API does support partial updates. Although I haven't tried it using ShopifySharp, but should just be a case of setting the properties you need. If your updating variants, you'd also need to pass the VariantId.

Cheers,
Shaun.

**Comment by nozzlegear** [comment]
@Infob has it right, you should be able to store just the product id in your database and update that product with a single call. That's what I do in my own Shopify apps to reduce bandwidth and database storage, and it works well. 

However, there is one gotcha that you should look out for: because of the way `int`, `bool`, `string` etc. works in C#, if you don't specify those values when updating your product they'll be sent as the default value (`0` for ints, `false` for bools, `""` for strings). If you don't set those values and send them as the default, Shopify may take them and overwrite whatever previous value you had.

The easiest way to prevent that is to grab the product from Shopify, make your changes to it and send the whole thing back with an update call (which ends up consuming 2 API calls like you said). 

Unfortunately, beyond manually preserving those values when you update your product, I don't have a quick fix for that; it's going to require setting all bools and ints to nullable in another major release.
