### ISSUE TITLE
Product "Unavailable"

### ISSUE THREAD

**Issue by Waqas2641995** [nozzlegear/ShopifySharp#491]
Hey,

when i update the product with "UpdateAsync" method so when i login on shopify store so updated product not appear on storefront , so issue is that when i update the product set as unavailable, i don't know why but it's happen. please help.

**Comment by nozzlegear** [comment]
Hey, this is something we run into often with this package due to the nature of JSON serialization in C#. It comes down to the fact that the `Product.PublishedAt` property, when not explicitly set, gets serialized to `null`. Shopify sees that and assumes you want to unpublish the project. 

The best way to fix this _right now_ is do pull in the entire Shopify product data from Shopify, set the properties you want to change, and then update it:

```cs
var product = await service.GetAsync(productId);

product.Title = "My new title";

product = await service.UpdateAsync(productId);
```

This will prevent Shopify from unpublishing the product, because when you pulled it in it had the `PublishedAt` property set to whatever the value is on the store. We're working on fixing this behavior in #477 and #388. 

(Note: depending on which version of ShopifySharp you're using, you might also need to set `product.InventoryQuantity = null` thanks to a deprecation in newer versions of Shopify's API. #484)
