### ISSUE TITLE
New property "checkout id" on Order object

### ISSUE THREAD

**Issue by mgrbec** [nozzlegear/ShopifySharp#496]
Hi,

as I see in Shopify documentation, there is property named "checkout_id" in Order object:
https://shopify.dev/docs/admin-api/rest/reference/orders/order

Is there any chance that you can add this property to Order? So we could retrieve it using API calls.

Thank you,
Matevž

**Comment by nozzlegear** [comment]
Hey! Unfortunately this isn't "officially" documented despite it being shown in the example responses on that page. The properties Shopify officially supports are the ones that are defined in the "Order Properties" section on that page. Usually when a property appears in the example responses like that, it's either because they're _planning_ to add it at some point in the future, or they removed it and have not yet updated the example response code. 

Regarding retrieving the checkouts via API, I'm not positive but I think this might not be the kind of checkout you're expecting. There are a couple different checkouts in Shopify's API (which is confusing), and I believe this one is for the "storefront" checkout ID, which is something you can't access via the REST API (as far as I know).
