### ISSUE TITLE
Working example of MetafieldService.ListAsync()?

### ISSUE THREAD

**Issue by danteotero** [nozzlegear/ShopifySharp#497]
Hi there,

Apologies if this is a simple question but I can't make the MatafieldService.ListAsync method work.  I've tried with code similar to the statement below but I'm getting 404 errors in return. Any ideas?

MatafieldService.ListAsync( 15245634545682, "product_image", 4733834531342, "products");

**Comment by nozzlegear** [comment]
The metafield API is somewhat confusing because of those strings you need to use. It might be useful in the future to break it up into multiple sub services like "ProductImageMetafieldService". I think for now though your issue might be the `product_image` string -- I'm pretty sure these strings need to be plural, so try changing it to `product_images` and let me know if that works!

```cs
MatafieldService.ListAsync( 15245634545682, "product_images", 4733834531342, "products");
```

**Comment by Spinks90** [comment]
> 
> 
> The metafield API is somewhat confusing because of those strings you need to use. It might be useful in the future to break it up into multiple sub services like "ProductImageMetafieldService". I think for now though your issue might be the `product_image` string -- I'm pretty sure these strings need to be plural, so try changing it to `product_images` and let me know if that works!
> 
> ```cs
> MatafieldService.ListAsync( 15245634545682, "product_images", 4733834531342, "products");
> ```
Thanks, that has just solved my issue. I was just struggling interpreting Shopify's obfuscated documentation.

My issue was to do with the **SmartCollection** resource name should have been **smart_collections**

**Comment by nozzlegear** [comment]
Glad you got it working!
