### ISSUE TITLE
data type for Shopify ID

### ISSUE THREAD

**Issue by pricerc** [nozzlegear/ShopifySharp#509]
I'm just conducting research for a client who is looking to integrate an in-house system with their Shopify site. 

I've created a new app, and I'm creating products. And everything's working fine.

But I noticed that according to the Shopify documentation, ID fields are UNSIGNED 64 bit. E.g. for @ [Product](https://shopify.dev/docs/admin-api/rest/reference/products/product?api[version]=2020-04):

```
id | An unsigned 64-bit integer that's used as a unique identifier for the product... 
```

However, the classes in ShopifySharp appear to have `long?` ID fields.

While 63 bits are a long way to go, is this a potential problem for the future, and should they not be `ulong?` fields?

**Comment by clement911** [comment]
That's a good point. I hadn't really thought of that.
By that same logic, there are also quite a few fields should be converted from int to uint because they can't be negative (e.g. `variant.grams`)
But, as you said, it's very unlikely to become a problem in practice. For long especially, 2^63 is an extremely large number that is extremely unlikely to ever be hit.
One thing to consider is that there are many methods in the .net framework that expect a int or long and don't have any overloads for uint and ulong. This makes it quite painful to work with unsigned types because you end up having to cast them to their signed counterpart.

**Comment by nozzlegear** [comment]
I agree with Clement. Ideally we could use the `ulong` or `uint` types, but it would cause a lot of tedious refactoring (both for the package and for package users) thanks to the lack of overloads/auto-coercing of the signed/unsigned types. It would have to be done in a major release like 6.0, but for now we should be safe with `long` for a very long time.
