### ISSUE TITLE
MissingMethod Exception

### ISSUE THREAD

**Issue by swood712** [nozzlegear/ShopifySharp#514]
Hi, I'm getting the following exception.

System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<ShopifySharp.Product> ShopifySharp.ProductService.UpdateAsync(Int64, ShopifySharp.Product, System.Threading.CancellationToken)'.'

Using ShopifySharp 5.1.0 on .NET Framework 4.7.2.
My URL is on /admin/api/2020-01.

Code as follows. The GetAsync method throws the exception. Am I missing anything obvious?

Thank you!

        public async Task SetTitle(long shopifyProductId, string title)
        {
            var shopifyProductService = new ProductService(_myShopifyUrl, _shopAccessToken);

            var product = await shopifyProductService.GetAsync(shopifyProductId);

            product.Title = title;
            product.PublishedAt = product.PublishedAt; // don't allow PublishedAt to be set to null

            await shopifyProductService.UpdateAsync(shopifyProductId, product);
        }

**Comment by swood712** [comment]
I've reverted to 5.0.4 and everything is working again now...

**Comment by nozzlegear** [comment]
This sounds like an issue with the package using a method that doesn't exist in .NET framework. The package does target the framework as one of its build targets though, so _theoretically_ this shouldn't happen. Unfortunately I'm not able to easily reproduce or debug this since I'm not using Windows and .NET framework doesn't work on Linux. 

If you create a new project using .NET Framework 4.7.2 and ShopifySharp 5.1.0, are you able to reproduce the problem? And if so, does the problem still exist on a project that uses .NET Core or .NET Standard?

**Comment by swood712** [comment]
I will check and report back...

**Comment by swood712** [comment]
Hi, I created a new Console App with .NET Framework 4.7.2 targeting ShopifySharp 5.1.0 and 5.1.1 and all is fine. So there must be some other dependency issue in my other solution...

**Comment by nozzlegear** [comment]
I'm actually getting this exception now myself when I use the `ShopifySharp.Experimental` package. Were you using that package as well?

**Comment by swood712** [comment]
No, I think there was some other dependency issue in my Web API project. I moved all my Shopify code into a separate class Library and upgraded to 5.1.1 and everything was fine after then. I believe it may have something to do with Microsoft.Extensions.Primitives. In my Web API, that was Version 2.0.0.0, now in the Shopify Library it's 1.1.0.0.

**Comment by dukeydukes** [comment]
I am facing the same issue, if rollback to 5.0.4 then it is fine but any other version since then has the same issue with the Method Not Found Error.

My project is targeted at .NET Core 3.1

Any suggestions or fixes to this? I've done the usual clean/rebuild/delete folders etc. I can quite easily transition between the Shopify Sharp versions to recreate it.

**Comment by dukeydukes** [comment]
I had the same issues and it was because I had a console app referencing a class library - both have ShopifySharp Nuget packages installed but they were different versions and I didn't realise. When I set them both to the same version then the problem is fixed. 
Hope this helps.

**Comment by nozzlegear** [comment]
@dukeydukes Thanks for the insight! 

I think this has arisen because we added an extra parameter to ShopifySharp's base [`ShopifyService.ExecuteRequestAsync`](https://github.com/nozzlegear/ShopifySharp/blob/c8a5b9cf4ba9770c62a2d1dfec102728cafb501f/ShopifySharp/Services/ShopifyService.cs#L148) method for passing in cancellation tokens. It seems this has introduced problems for class libraries and other packages that depend on ShopifySharp -- if they're built for the version of ShopifySharp that _doesn't_ have that new parameter, they'll throw this exception because nuget might install a newer version. 

That's the case for ShopifySharp.Experimental -- at some point I accidentally published a full 5.0 version of it instead of a prerelease, and this 5.0 version was built when ShopifySharp didn't have that parameter. However, nuget doesn't know anything about that, so it sees the Experimental package wants version >= 5 and just gives us the latest ShopifySharp. 

I'm not sure what the fix is for this except to make sure you're using at least ShopifySharp 5.1 where the new parameter was introduce. I don't know if publishing a new version that adds the old method (sans cancellation token parameter) back in would fix the problem.

**Comment by Smartisa** [comment]
> @dukeydukes Thanks for the insight!
> 
> I think this has arisen because we added an extra parameter to ShopifySharp's base [`ShopifyService.ExecuteRequestAsync`](https://github.com/nozzlegear/ShopifySharp/blob/c8a5b9cf4ba9770c62a2d1dfec102728cafb501f/ShopifySharp/Services/ShopifyService.cs#L148) method for passing in cancellation tokens. It seems this has introduced problems for class libraries and other packages that depend on ShopifySharp -- if they're built for the version of ShopifySharp that _doesn't_ have that new parameter, they'll throw this exception because nuget might install a newer version.
> 
> That's the case for ShopifySharp.Experimental -- at some point I accidentally published a full 5.0 version of it instead of a prerelease, and this 5.0 version was built when ShopifySharp didn't have that parameter. However, nuget doesn't know anything about that, so it sees the Experimental package wants version >= 5 and just gives us the latest ShopifySharp.
> 
> I'm not sure what the fix is for this except to make sure you're using at least ShopifySharp 5.1 where the new parameter was introduce. I don't know if publishing a new version that adds the old method (sans cancellation token parameter) back in would fix the problem.

Is there any way to know that there are API changes in the currently installed package version? How do I know the correct version of compatibility?
