### ISSUE TITLE
Version mismatch issue when upgrading to ShopifySharp 5.3

### ISSUE THREAD

**Issue by HoomanBahreini** [nozzlegear/ShopifySharp#529]
Hi

Not sure if this problem specific to my application, but when I upgraded ShopifySharp to 5.3 today, I started getting the following error when executing: `AuthorizationService.IsAuthenticRequest(...)`

> Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

I have reverted my package back to 5.1 and it is working again.

**Comment by nozzlegear** [comment]
Thanks for letting me know about this! I've had some issues with version mismatches misbehaving recently. I don't think it's specifically anything to do with ShopifySharp, but more with the way dotnet/nuget decide which versions of packages to install. In my case, it seems the Microsoft.AspNetCore.All package is always the culprit since it installs a gigantic number of other packages under the hood. Happy to open this issue back up if anyone things the problem is with ShopifySharp or can suggest a way to prevent this from happening!
