### ISSUE TITLE
Accessing Menus via API

### ISSUE THREAD

**Issue by JoePlant** [nozzlegear/ShopifySharp#549]
I have a complicated menu structure that I am looking to solve.
Has anyone been able to programmatically access the shopify store menu structures from code?

Some options I am considering -
 - accessing the menu structure to detect any menu inconsistencies
 - Using an API to programatically update the menu as new collections are being added.

Background - 
We currently have about 40+ collections and each need to be in the menu.  Each collection also has a supporting page providing an alternative way of accessing it. 

Currently we have 2 sub menus "By Collection" and "By Page". Each collection is listed in a single list but it is getting too large (40+ menu items).  I can easily group these into about 5-7 groupings and would like to synchonise the structure 

For example, I want to have to main menus
Home
By Collection 
 > Group 1 
   - Collection 1A
   - Collection 1B

 > Group 2
   - Collection 2A
   - Collection 2B
 
By Page 
 > Group 1 
   - Page 1A
   - Page 1B

 > Group 2
   - Page 2A
   - Page 2B

**Comment by nozzlegear** [comment]
Hey! Unfortunately I don't personally work with collections and products very much, so I'm not sure I have a good solution for this. I'd love to hear if you manage to get this to work, or if anyone else reading this has some advice!

**Comment by foxandrewj** [comment]
What you are looking for is to update the Link Lists (used for navigation) through the API, but unfortunately they can't be accessed though people have been asking for this for quite some time.[ https://community.shopify.com/c/Shopify-APIs-SDKs/Where-is-the-LinkList-API-endpoint/td-p/502347]( https://community.shopify.com/c/Shopify-APIs-SDKs/Where-is-the-LinkList-API-endpoint/td-p/502347)

An idea that I have seen put forth, though never implemented myself, is to push your menu data into a snippet and save it into the theme. Then update the header.liquid navigation code to parse the menu data from the snippet instead of the pulling the linklists stored in he admin.

**Comment by JoePlant** [comment]
Thanks for your comments on this issue.  It is a tricky thing to manage and would require more changes to the store. 
At the moment, this is just being managed manually throught the shopify admin.
