### ISSUE TITLE
UpdateASync - turns product off from online store, how to specify that product needs to be live?

### ISSUE THREAD

**Issue by zhorakiev** [nozzlegear/ShopifySharp#554]
UpdateASync - turns product off from online store, how to specify that product needs to be live? 

 ShopifySharp.Product product = await ProdServ.UpdateAsync((long)prod.Id, new ShopifySharp.Product()
                {
                    Title = sProdTitle.Trim(),
                    Tags = sjoin,
                    Options = ??????

                });

**Comment by ChaoticIke** [comment]
You would need to set PublishedAt to a value. If it is set to null (the default) then the product gets unpublished.

[Comment in Source](https://github.com/nozzlegear/ShopifySharp/blob/5adfe70911b7f7e061fdee19efe505ffa3c2aa3e/ShopifySharp/Entities/Product.cs#L45)

**Comment by nozzlegear** [comment]
Yes, this is an unintended behavior that I'd like to fix eventually, but right now the product will be unpublished if you do not specifically set a `PublishedAt` property. It's due to the sometimes unintuitive JSON serialization of C# objects, and I'm exploring a few different methods to fix it. Here's what you need to do specifically to stop them from being unpublished:

```cs
DateTimeOffset publishedDate = DateTimeOffset.Now; 
ShopifySharp.Product product = await ProdServ.UpdateAsync((long)prod.Id, new ShopifySharp.Product()
{
	Title = sProdTitle.Trim(),
	Tags = sjoin,
	Options = ??????,
	PublishedAt = publishedDate
});
```

You might want to preserve the current `PublishedAt` date, so you'd probably pull in the product before updating it with `ProdServ.GetAsync((long) prod.Id)` and then use its `PublishedAt` property when updating.
