### ISSUE TITLE
Refused to Display in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by Engr-Waleed-Saddique** [nozzlegear/ShopifySharp#633]
App is not opening after installation and in console showing this message.

**Comment by nozzlegear** [comment]
Hey @Engr-Waleed-Saddique, I'm going to close this because it's most likely an issue with ASP.NET and the AntiForgyerToken configuration rather than ShopifySharp itself (and also because this issue is 9 months old 😅). If you or anyone in the future is wondering how to fix this problem, you need to configure ASP.NET to not send the `X-Frame-Options` header when using antiforgery tokens:

```cs
// In Startup.cs (or wherever you configure your asp.net services)

services.AddAntiforgery(c =>
{
    c.SuppressXFrameOptionsHeader = true;
});
```
