### ISSUE TITLE
SmartRetryExecutionPolicy leak rate calculation

### ISSUE THREAD

**Issue by KorsG** [nozzlegear/ShopifySharp#655]
Hi 

I am working on an integration for a shop which have their rate limit increased, so their bucket size is 240 and leak rate is 12, but the SmartRetryExecutionPolicy does not seem to calculate the leak rate correctly. 

If the bucket size is larger than the default (40) it takes the size / 40, which in this case results in a leak rate of 6 instead of 12.
For Plus customers which have a bucket size of 80 it results in a leak rate of 2, but it should be 4. 

Reference: https://shopify.dev/api/usage/rate-limits#rest-admin-api-rate-limits
![image](https://user-images.githubusercontent.com/1583564/127540840-d2fc5669-0121-4a80-b9d7-02d9c6234d6e.png)

According to this forum post, the correct implementation is to always divide the bucket size by 20:
https://community.shopify.com/c/Shopify-APIs-SDKs/What-is-the-default-API-call-limit-on-Shopify-stores/m-p/338875/highlight/true#M17384

Example:
40/20: 2
80/20: 4
240/20: 12

This line should therefore divide by 20 instead of the default bucket size of 40, unless I have totally misunderstood 😊
https://github.com/nozzlegear/ShopifySharp/blob/91a646339f1c12d300d7a9854beaa3cbc49ca5c5/ShopifySharp/Infrastructure/Policies/SmartRetryExecutionPolicy.LeakyBucket.cs#L48

**Comment by clement911** [comment]
Hi.

You've overlooked the fact that the 'THROTTLE DELAY' is set to 500ms, so this is really a leak rate per half second. To calculate the leak rate per second, you should multiply by 2, and will get the correct result..

In other words, dividing by 20 gives you the rate per second. But because we drip the buckets every half second, we divide by 40 instead.

See https://github.com/nozzlegear/ShopifySharp/blob/91a646339f1c12d300d7a9854beaa3cbc49ca5c5/ShopifySharp/Infrastructure/Policies/SmartRetryExecutionPolicy.cs#L30

I hope this all makes sense?

**Comment by KorsG** [comment]
Hi @clement911, that makes perfectly good sense then, sorry for doubting the logic 😀 - thanks for explaining and have a great day 😊

**Comment by clement911** [comment]
No problem at all, it's always good to have others review the logic.
