### ISSUE TITLE
Error when using IsAuthenticWebhook

### ISSUE THREAD

**Issue by davitgr** [nozzlegear/ShopifySharp#683]
I have a webhook endpoint that uses `AuthorizationService.IsAuthenticWebhook` to validate, and each time it fails. I am using .NET 5. Below is a snippet of the endpoint I have:

```
        [HttpPost("app/uninstall")]
        public async Task<IActionResult> ProcessShopifyAppUninstallWebhook([FromBody] Shop request,)
        {
            try
            {
                if (await AuthorizationService.IsAuthenticWebhook(Request.Headers, Request.Body,
                    _shopifySettings.Value.SecretKey))
                {
                    return Ok();
                }

                return BadRequest();
            }
            catch (Exception e)
            {
                return StatusCode(500);
            }
```

When it calls IsAuthenticWebhook, an exception is thrown, `Specified method is not supported.`. I would appreciate any help to resolve the issue that I'm having.

**Comment by nozzlegear** [comment]
Ah okay, so there are two problems going on here:

1. The request stream is not rewindable by default in aspnet, which means if the body is read once it cannot be read again and will just return an empty string. In your code, aspnet is reading the body to turn it into a `Shop` instance with `[FromBody] Shop request`).
2. ShopifySharp is attempting to rewind the request body so it can read it, but this is throwing an exception because it's not rewindable. 

There are a few ways you can fix this, but I'd recommend removing the `Shop` parameter and instead create a method that will read a request's body to a string. You can then use that string to deserialize into a `Shop` instance yourself, _and_ you can pass the string directly to ShopifySharp for validation so it doesn't need to deal with the request stream.

Here's what that would look like:

```cs
async Task<string> ReadBodyAsStringAsync(HttpRequest req)
{
	// Request streams can only be read once by default. This method enables multiple reads of the request.
	req.EnableBuffering();
	
	var stream = req.Stream;
	string bodyStr;
	
	await using (var buffer = new MemoryStream())
	{
		await stream.CopyToAsync(buffer));

		// Move the buffer position back to 0. If we don't do this, the streamreader will just read an empty string
		buffer.Position = 0;

		using (var reader = new StreamReader(buffer))
		{
			bodyStr = await reader.ReadToEndAsync()
		}
	}
	
	if (stream.CanSeek)
	{
		stream.Position = 0;
	}
	
	return bodyStr;
}
```

And then you can use it like this:

```cs
[HttpPost("app/uninstall")]
public async Task<IActionResult> ProcessShopifyAppUninstalledWebhook()
{
	var body = await ReadBodyAsString(Request);
	var isValid = await AuthorizationService.IsAuthenticWebhook(Request.Headers, Request.Body, _shopifySettings.Value.SecretKey);
	
	if (!isValid) 
	{
		// Request is not authentic
	}
	else
	{
		// Request is authentic, deserialize the body to a Shop instance
		var shop = ShopifySharp.Infrastructure.Serializer.Deserialize<Shop>(body);
	}
}
```

**Comment by davitgr** [comment]
@nozzlegear Thank you very much. This resolved the issue
