### ISSUE TITLE
Orders.ListAsync with Ids filter doesn't return all orders

### ISSUE THREAD

**Issue by incoventures** [nozzlegear/ShopifySharp#700]
Some orders are not returned via ListAsync if you add their ids in the filter but I can retrieve them via GetAsync 

`            var filter = new OrderListFilter()
            {
                Ids = new List<long>() { 4598387540209, 4599294853361, 4600883773681}
            };
            var orders = await shopifyOrders.ListAsync(filter);
//returns only 4598387540209
            var tmp = await shopifyOrders.GetAsync(4599294853361);`
//returns order 4599294853361

**Comment by nozzlegear** [comment]
Hey @incoventures, did you get this fixed? I believe the problem is that listing orders will only return open orders by default, so if one of the orders you're trying to list is closed/fulfilled/canceled then it won't be returned in this list. You can fix it like this:

```cs
var filter = new OrderListFilter
{
	Ids = new List<long>() { ... },
	Status = "any"
}
```

Let me know if that works for you!

**Comment by incoventures** [comment]
Yes, I figured that out. Thank you!
