### ISSUE TITLE
New rate limits for API

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#774]
Hi,

I see in the documentation that Shopify has changed the API rate limits:

**The REST Admin API supports a limit of 40 requests per app per store per minute. This allotment replenishes at a rate of 2 requests per second. The rate limit is doubled for Shopify Plus stores.**

Is this implemented in ShopifySharp?

**Comment by nozzlegear** [comment]
Hey @davidkdb, thanks for letting me know about this. I wasn't aware that Shopify had changed the rate limits, do you have a link to that documentation?

**Comment by nozzlegear** [comment]
@clement911 Just want to make sure I understand the execution policies you implemented. Am I right in assuming new rate limits should be handled by the policies automatically since they read the limit from the response headers? We don't hardcode a limit of 20 per second anywhere as far as I can tell.

**Comment by davidkdb** [comment]
Link to the article:

https://shopify.dev/api/admin-rest#rate_limits

**Comment by nozzlegear** [comment]
Thanks! It looks like the [`LeakyBucketExecutionPolicy` does indeed handle the increased rate for Shopify Plus stores](https://github.com/nozzlegear/ShopifySharp/blob/483ceaf61b4769caea5c99fab9618b06b2989ef1/ShopifySharp/Infrastructure/Policies/LeakyBucketPolicy/MultiAPIBucket.cs#L36). As long as you're using that policy it should adjust itself automatically!

**Comment by clement911** [comment]
Yes I confirm that the rate will adjust dynamically based on the header "X-Shopify-Shop-Api-Call-Limit" returned by the API.

https://github.com/nozzlegear/ShopifySharp/blob/65a9c7a38f4769d7b5d86d268eee0882136c23ee/ShopifySharp/Infrastructure/Policies/LeakyBucketPolicy/LeakyBucketExecutionPolicy.cs#L116

However, I can't find anything that changed. The rates are 40 by default and 80 for Plus stores, which was already the case.
@davidkdb are you saying something changed recently because as far as I can see, it's the same as ever.

**Comment by davidkdb** [comment]
You probably right. They probably just have changed the explanation.
