### ISSUE TITLE
OrderService.UpdateAsync doesn't update LineItems

### ISSUE THREAD

**Issue by petrechitashvili** [nozzlegear/ShopifySharp#792]
We are looking for ways to allow editing Orders created by ShopifySharp either through the API or from within the Admin UI of Shopify.

OrderService.UpdateAsync updates some fields but not LineItems.

Editing an order from the Admin UI produces this error:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/15320885/194507864-ed33f36b-7230-4935-87c5-2a957a4105de.png">

There is a `ShopifySharp.OrderEdit` class but didn't see how to use it.
Shopify's GraphQL documentation claims it's possible to make some edits but didn't see a way to edit LineItems.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/15320885/194508894-4ac11cac-5278-43ae-a99a-dd9f836853ae.png">

Can you point in the right direction of how to edit orders created through ShopifySharp?

Much appreciated!

**Comment by nozzlegear** [comment]
Hey @petrechitashvili! Thanks for the question, it looks like you're on the right track with the GraphQL stuff. Unfortunately editing the line items of an order is only available with the GraphQL API, which (due to the dynamic nature of the queries and mutations being sent and received in Graph calls) isn't as well supported with classes/services in ShopifySharp. 

That said, with ShopifySharp's GraphService you should be able to do everything you need to do with the Graph API as long as you're happy making you're happy writing the mutations and queries! I've had a look at the docs for editing an order, and I think you should be able to edit a line item by doing something like this:

```cs
            var graphService = new GraphService(Utils.MyShopifyUrl, Utils.AccessToken);
            // Note the escaped quotation marks!
            var orderId = "\"gid://shopify/Order/4859541618791\"";
            var mutation = await graphService.PostAsync($@"
                mutation beginEdit {{
                    orderEditBegin(id: {orderId}) {{
                        calculatedOrder {{
                            id
                        }}
                    }}
                }}
            ");
            var editedOrderId = mutation.SelectToken("orderEditBegin.calculatedOrder").Value<string>("id");
            // Note the escaped quotation marks!
            editedOrderId = $"\"{editedOrderId}\"";
            
            // Continue your order edit here
            
            // Commit the edit
            var staffNote = "\"Order was edited by XYZ app\"";
            var commit = await graphService.PostAsync($@"
                mutation commitEdit {{
                    orderEditCommit(id: {editedOrderId}, notifyCustomer: false, staffNote: {staffNote}) {{
                        order {{
                            id
                        }}
                        userErrors {{
                            field
                            message
                        }}
                    }}
                }}
            ");
            var errors = commit.SelectTokens("userErrors");

            if (errors.Any())
            {
                var firstError = errors.First();
                var field = firstError.Value<string>("field");
                var message = firstError.Value<string>("message");
                
                throw new Exception($"Shopify GraphQL error: ({field}) {message}");
            }

```

You can use any of those `orderEdit*` mutations once you've begun the mutation. Also note that you can only edit **unfulfilled** line items, you can't edit anything that's already been fulfilled.

[Here's Shopify's short guide to editing an order using GraphQL](https://shopify.dev/apps/fulfillment/order-management-apps/order-editing), which has some more useful information.

--- 

As for the OrderEdit class in ShopifySharp, that's just a class we've added for data received from the OrderEdit webhook. It's unfortunately not used for the actual editing of orders.

Let me know how that works for you!

**Comment by petrechitashvili** [comment]
Thanks for the extensive answer, @nozzlegear!

I'll look into it and get back to you.

**Comment by petrechitashvili** [comment]
Hey @nozzlegear, just reporting to let you know that editing LineItems did work with the help of your guidance, thank you for that!

Out of curiosity, do you know why LineItem editing would be supported via GraphQL but not REST?
