### ISSUE TITLE
How to get new Orders efficient?

### ISSUE THREAD

**Issue by Azorus93** [nozzlegear/ShopifySharp#813]
Hey there,
I am working on a crawler to add new shopify orders to my system. 
The only way I can see to do this is to query the order count, compare it to the previous count and if the counter is higher, do a list query.
So 
int orderCount = await orderservice.CountAsync();
and
if(orderCount > oldOrderCount)
ShopifySharp.Lists.ListResult <Order> orders = await orderservice.ListAsync();

However, this seems very inefficient to me, to query all orders in a list every time to get only the latest ones.

Any example would be very helpful.
Thanks

**Comment by nozzlegear** [comment]
Hey @Azorus93! Have you looked into using webhooks for this? If you set up a new webhook for the "orders/create" event, Shopify will send you an HTTP post request each time a new order is created on a shop. The request body will contain the new order so you can process it. 

Here's an example for setting up the webhook:

```cs
var service = new WebhookService(shopDomain, accessToken);

await service.CreateAsync(new Webhook
{
    Address = "https://myapp.com/webhooks/order-created",
    Topic = "orders/create"
});
```

(Note that you need to create a webhook for every shop you're working with -- each webhook is tied to that shop domain the service is using.)

Then you'd set up an http handler at that `/webhooks/order-created` url to wait for new HTTP requests. If you're using asp.net you'd do it like this:

```cs
public class Controller : Controller
{
    [Route("/webhooks/order-created")]
    public async Task<IActionResult> OrderCreated([FromQuery] string shop)
    {
        // Validate the request using Shopify's validation scheme
        var body = await ReadRawBodyAsync();
        var headers = Request.Headers;
        var isAuthentic = AuthorizationService.IsAuthenticWebhook(headers, body, shopifySecretKey);

        if (!isAuthentic) 
        {
            return Forbidden("Request did not pass Shopify's validation scheme.")
        }

        // Request is valid, parse the body into a ShopifySharp order
        var order = ShopifySharp.Infrastructure.Serialization.Deserialize<ShopifySharp.Order>(body);

        // Do what you need to do with the order
    }

    /// <summary>
    /// Reads the request stream into a string, while simultaneously ensuring request handlers further down the pipeline can still use the request stream without it being disposed or stuck at the end.
    /// </summary>
    private async Task<string> ReadRawBodyAsync()
    {
        // Request streams by default can only be read once. This method enables multiple reads for this request.
        Request.EnableBuffering();

        var stream = Request.Body;
        string rawBody;

        // While the stream can now be rewound, using streamreader will automatically dispose it which we don't want.
        // Instead we need to copy the stream to another temporary stream that can be safely disposed without disposing the request.
        using (var buffer = new MemoryStream())
        {
            await stream.CopyToAsync(buffer);

            // Move the buffer position back to 0. If we don't do this, 
            // the streamreader will just read an empty string.
            buffer.Position = 0;

            using (var reader = new StreamReader(buffer))
            {
                rawBody = await reader.ReadToEndAsync();
            }
        }

        if (stream.CanSeek)
        {
            stream.Position = 0;
        }

        return rawBody;
    }
}
```

That's what I would personally do. However, if you can't use webhooks for whatever reason, I believe you can use ShopifySharp's `OrderListFilter` class and pass in the `SinceId` or `CreatedAtMin` fields. If you do that, you'd only be listing orders that have been created since the last ID you recorded or that have been created since the date you give the filter, respectively:

```cs
var service = new OrderService(shopDomain, accessToken);
var filter = new OrderListFilter
{
    SinceId = lastOrder.Id
}
var ordersCreatedSinceLastId = await service.ListAsync(filter);
```

Let me know if either of those solutions work for you!

**Comment by Azorus93** [comment]
Fantastic! Thousand thanks <3
