### ISSUE TITLE
Package ShopifySharp 5.14.0 is not compatible with net60 

### ISSUE THREAD

**Issue by madushann** [nozzlegear/ShopifySharp#823]
Due to the value_type update in Shopify API I have to update ShopifySharp version in some of my projects. Where it lead to whole set of upgrade issues with incompatibilities. Due to Azure storage and other microsoft package dependancies in the project after spending a week or so I found only option is to go with .Net6 azure functions. Now when I upgrade the projects to .Net6, locally everythings works fine but when I tried to deploy the project in Azure Devops pipeline I get the below error

> Package ShopifySharp 5.14.0 is not compatible with net60 (.NETFramework,Version=v6.0). Package ShopifySharp 5.14.0 supports: netstandard2.1 (.NETStandard,Version=v2.1) 

Does Shopifysharp supports .Net6 ?

**Comment by nozzlegear** [comment]
Hey, that's really strange. .NET 6.0 itself is compatible with and implements .NET Standard 2.1 which means they're fully compatible and this error sounds flat out wrong. In fact I use ShopifySharp with .NET 6+ in several projects right now, and ShopifySharp's own test projects in this repo are using .NET 6. 

You can see the .NET Standard compatibility matrix here: https://dotnet.microsoft.com/en-us/platform/dotnet-standard

I think this sounds like an issue with Azure DevOps especially since it's working locally for you, but unfortunately I don't know where you'd look to start debugging that. I'm sorry I can't be more help!

--
Josh Harms

**Comment by madushann** [comment]
Thank you @nozzlegear 

I have updated all other dependencies to .Net6 to check if somethings going on with them but even after updating them all, it still gives the same error. I may try to check with Azure Devops see if I can find something here.

**Comment by madushann** [comment]
I have managed to solve the issue. 
Actually it was due to the NuGet install version. I have made it to the latest version and it build successfully.

**Comment by nozzlegear** [comment]
Awesome, I'm glad to hear you got it working! Let me know if you have any other issues with the package, I'd be happy to help.

--
Josh Harms
