### ISSUE TITLE
Order GetList Filter PageInfo only get,why not set?

### ISSUE THREAD

**Issue by lei-9** [nozzlegear/ShopifySharp#910]
![image](https://github.com/nozzlegear/ShopifySharp/assets/28752083/a49c770f-8b3a-4e1a-a753-1ca9a154719e)

only use ListFilter Query?

**Comment by nozzlegear** [comment]
Hey @lei-9! I believe it's explained more here in #462. I think the reasoning was that Shopify at the time recommended developers do not store the `PageInfo` value anywhere since it can change at any time. So to make sure people using ShopifySharp weren't going to shoot themselves in the foot we thought we'd make the property only gettable and then require everyone to use the `GetNextPageFilter` and `GetPreviousPageFilter` methods.

However, you can use the constructors for the more specific list filters like `OrderListFilter` and `ProductListFilter` to pass in the `PageInfo` value, so that kind of defeats the purpose. And as discussed in that issue, there are legitimate use cases like your users navigating from one page of their orders to the next using the `PageInfo` value in your querystring.

@clement911 does that sound right? Do you remember why we set it to get-only?

**Comment by clement911** [comment]
Yes, that sounds right to me. @lei-9 you can use the ListFilter constructor if you want to set the PageInfo.

![image](https://github.com/nozzlegear/ShopifySharp/assets/3426504/eb3e7067-6341-4f56-9219-d73c0dfc6f31)

**Comment by lei-9** [comment]
tk~
